### ISSUE TITLE
Use node 20 runner

### ISSUE THREAD

**Issue by el-timm** [einaregilsson/beanstalk-deploy#108]
Github is now outputting this warning.

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: einaregilsson/beanstalk-deploy@v21. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by tiagojsag** [comment]
https://github.com/einaregilsson/beanstalk-deploy/issues/93

**Comment by gzur** [comment]
Fixed by #106
