### ISSUE TITLE
[Feature Request] Add Param To Ignore Polling Altogether

### ISSUE THREAD

**Issue by kceb** [einaregilsson/beanstalk-deploy#13]
First off, thanks for this action, it is invaluable and thanks for being so responsive to issues.

I was wondering if we could could add something like the `WAIT` parameter here and default it to `true`: https://confluence.atlassian.com/bitbucket/deploy-to-aws-with-elastic-beanstalk-976772710.html

Reason I ask: Immutable deployments take a long time and eat up Github Action minutes.

**Comment by einaregilsson** [comment]
Good idea. Have just implemented it in v9, it's just been released. Parameter is called `wait_for_deployment`, defaults to `true`. 

> it is invaluable and thanks for being so responsive to issues.

Thanks! It's a way to learn something new, and force myself to make decent deployment scripts by making a re-usable action out of them. 😉
