### ISSUE TITLE
ElasticBeanstalk Description for deployment [suggestion]

### ISSUE THREAD

**Issue by lfreneda** [einaregilsson/beanstalk-deploy#14]
Would be nice a property to set deployment description:

![image](https://user-images.githubusercontent.com/372420/77761804-5c1a2f00-7017-11ea-862e-3b4d2a877ef3.png)

**Comment by einaregilsson** [comment]
Sounds useful. I'll try to get it in the next version 🙂

**Comment by lfreneda** [comment]
> Sounds useful. I'll try to get it in the next version

Thanks! Would be really useful :)

Keep with your nice work <3

**Comment by andreisusanu** [comment]
+1

**Comment by einaregilsson** [comment]
This has been added in version 10 which I've just released. The parameter name is `version_description`.
