### ISSUE TITLE
every step must define a uses or run key

### ISSUE THREAD

**Issue by neutmute** [einaregilsson/beanstalk-deploy#2]
Hey there
Thank you for this plugin. I've tried taking it and commiting it to my repo, adding the AWS secrets etc but github refuses to run it. The error is

> every step must define a uses or run key

![image](https://user-images.githubusercontent.com/1303131/69213461-4653b380-0bb8-11ea-9c77-993b87754006.png)

I have literally the same file as in the documented sample except for lines 23 to 25 where I made some obvious string literal changes to suit my env - the `version_label` is hardcoded to `1`

```        
        application_name: MyApplicationName
        environment_name: MyApplication-Environment
        version_label: 12345
```

Any suggestions?

**Comment by einaregilsson** [comment]
Ok, I looked into it and the example had an error. It had:

```
    - name: Checkout source code
    - uses: actions/checkout@v1
```

So both ```-name``` and ```-uses``` started with a -, which lets yaml interpret them as seperate items. It should have been:

```
    - name: Checkout source code
       uses: actions/checkout@v1
```

which says that it's one item with a name, and the uses belongs to the same step. I've updated the example. Also, you should use the @v3 of the action now, it has some improvements around handling errors. I've updated the example to also use that. (Or you can use @master although then there might be breaking changes at some point).

**Comment by neutmute** [comment]
Fantastic - thanks very much.

**Comment by coolcorexix** [comment]
If you are using VSC, I recommend using this extension - it helped validate the yaml file
https://marketplace.visualstudio.com/items?itemName=me-dutour-mathieu.vscode-github-actions
