### ISSUE TITLE
Re-running failed deployments

### ISSUE THREAD

**Issue by andreubotella** [einaregilsson/beanstalk-deploy#20]
I've run today into a case similar to #19, where the deployment failed because I'd just changed the environment configuration, but re-running the job subsequently wouldn't work because that version label already existed. I know I can change the current version manually, but not everyone with commit access to this repo has access to the AWS, so they should be able to re-run the jobs and have it work.

Since this is something not everyone might want, it'd be better to have it as a flag.

**Comment by einaregilsson** [comment]
You could achieve this by setting the `use_existing_version_if_available` to `true`. From the docs:

> use_existing_version_if_available: This can be set to true and then the program will deploy a version already in Elastic Beanstalk if it exists, but if it doesn't exist it will create it from the deployment package you specify. This can be useful when deploying to multiple environments, based on commit message. See issue https://github.com/einaregilsson/beanstalk-deploy/issues/8 for example. This parameter is new in version 5, and is optional, if you omit it the program will simply behave exactly as it did before, by looking at the existence of deployment_package to decide whether to create a version or not.

Personally I don't like it, I want a run to either succeed or fail and I never rerun the same job, I would always start a new job, but the option is there for those that want it.

**Comment by andreubotella** [comment]
My bad, when I read about that option I was left with the impression that it would do nothing when attempting to deploy an existing version. Closing this issue, then.
