### ISSUE TITLE
Deployment failed due to 400 / empty message

### ISSUE THREAD

**Issue by jadekler** [einaregilsson/beanstalk-deploy#24]
See: https://github.com/jadekler/php-aws/runs/707781910

```
Uploading file to bucket elasticbeanstalk-af-south-1-597857118726
##[error]Deployment failed: Error: Status: 400. Message:
```

Any idea what gives?

**Comment by jadekler** [comment]
I think it has to do something with the 12345 version. When I set `use_existing_version_if_available=true` and plug in my existing version, it works.

**Comment by jadekler** [comment]
I take that back: it appears to work, but the application doesn't actually get updated to the new version. 🤔

**Comment by einaregilsson** [comment]
Hmm, not sure. But did you already have a version 12345 in Elastic Beanstalk? Have you tried with a different version number?

**Comment by jadekler** [comment]
> did you already have a version 12345 in Elastic Beanstalk?
I did not.

> Have you tried with a different version number?
I did, and same result.

------------

I was able to resolve this by just using some bash to perform the upload:

```
    - name: Deploy to beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: af-south-1
        EB_ENV_NAME: Mycloudapp-env
      run: |
        # Install AWS and EB CLI.
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        sudo apt-get install -y build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev
        git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
        ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer
        echo 'export PATH="/home/runner/.ebcli-virtual-env/executables:$PATH"' >> ~/.bash_profile && source ~/.bash_profile
        # Deploy.
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region AWS_REGION
        zip deploy.zip -r * .[^.]* -x "vendor/*"
        eb deploy $EB_ENV_NAME
```

**Comment by fedealconada** [comment]
Is it possible to have a dynamic name for the `versions_label`? So I don't have to be modifying the .yaml file each time I want to trigger a deployment... @einaregilsson

**Comment by einaregilsson** [comment]
@fedealconada What do you mean? You can always use some variable from a previous step as your version label. I don't really understand what you're asking for, can you clarify? What is the workflow you want to achieve?

**Comment by einaregilsson** [comment]
Haven't heard this from anyone else. Closing this issue, will re-open if more people have this problem.

**Comment by dryleaf** [comment]
@einaregilsson I am also experiencing this issue, I thought it was kind of formatting or something but all my attempts have seemed to fail. Please check my build below.
- https://github.com/dryleaf/spring-boot-data-jpa-mysql/runs/1371760308?check_suite_focus=true

I only got a successful redeploy of an existing version which I deployed manually using the aws `eb` command.
- https://github.com/dryleaf/spring-boot-data-jpa-mysql/runs/1363077502?check_suite_focus=true

Error message:
```
Run einaregilsson/beanstalk-deploy@v14
Beanstalk-Deploy: GitHub Action for deploying to Elastic Beanstalk.
https://github.com/einaregilsson/beanstalk-deploy

 ***** Input parameters were: ***** 
         Application: spring-boot-data-jpa-mysql
         Environment: spring-boot-dev
       Version Label: v1.12
 Version description: 
          AWS Region: af-south-1
                File: ./target/spring-boot-data-jpa-mysql.zip
      AWS Access Key: 20 characters long, starts with A
      AWS Secret Key: 40 characters long, starts with p
 Wait for deployment: true
  Recovery wait time: 30

Uploading file to bucket elasticbeanstalk-af-south-1-967450361901
Error: Deployment failed: Error: Status: 400. Message: 
```

**Comment by einaregilsson** [comment]
Ok, so it's the S3 upload causing the problem, since the redeploy worked. The application and environment names don't seem to have any characters that should cause trouble. Couple of things to try:

1. What if you try with a version label like 2. Of course the . should work, but this sounds like an encoding issue and so it pays to test all possibilities.

2. The filepath, `./target/spring-boot-data-jpa-mysql.zip`, you're absolutely sure that it's correct? Try changing it to some garbage, e.g. `./notexist.zip`, see if you get the same error. I checked the code, I don't really do a good job of checking if the file exists, so I'm wondering if there's a path issue and we're not sending the file with the request.

Other than that I don't know. Error messages from AWS don't say much, so you're left trying to just try different things and seeing what works :)

**Comment by dryleaf** [comment]
I did replace the version label field as in:
- https://github.com/dryleaf/spring-boot-data-jpa-mysql/runs/1373460431?check_suite_focus=true
- https://github.com/dryleaf/spring-boot-data-jpa-mysql/runs/1373582304?check_suite_focus=true
The error message still the same.
>1. What if you try with a version label like 2. Of course the . should work, but this sounds like an encoding issue and so it pays to test all possibilities.

I also changed to some non-existing package, the error message complains about file not being found
- https://github.com/dryleaf/spring-boot-data-jpa-mysql/runs/1373550057?check_suite_focus=true
  - `Error: Deployment failed: Error: ENOENT: no such file or directory, open './target/demo.zip'`
>2. The filepath, ./target/spring-boot-data-jpa-mysql.zip, you're absolutely sure that it's correct? Try changing it to some garbage, e.g. ./notexist.zip, see if you get the same error. I checked the code, I don't really do a good job of checking if the file exists, so I'm wondering if there's a path issue and we're not sending the file with the request.

**Comment by einaregilsson** [comment]
Ok. Sorry, don't have many ideas left. Try a different region, us-west-2 for example, see if that works?

**Comment by Niko-Kk** [comment]
I was having the same issue. Without looking the open pull requests, I came to the same code edits as this PR (https://github.com/einaregilsson/beanstalk-deploy/pull/47), and it now works. I'll be running of my forked version for now, but this solved the issue for me.

My region is also af-south-1 so it might be a regional problem if no others are experiencing it.

**Comment by dryleaf** [comment]
Yes. Seems like this workflow does not yet support south africa region. I ended up changing into a different solution.

**Comment by einaregilsson** [comment]
@Niko-Kk Guess I'll have to make an app in south africa region and see 🙂

**Comment by dryleaf** [comment]
The aws servers are there. Lol

**Comment by OliverRC** [comment]
I got these the same `Error: Deployment failed: Error: Status: 400. Message: ` when trying to do a deployment to `af-south-1`.
The error disappears entirely when deploying to another region e.g `us-east-2`.

What? I am encountering a lot of weirdness with the South African region.

**Comment by einaregilsson** [comment]
Not sure why that is. But I know for China we had to use a slightly different server name that ends with .cn. Anything in the docs about something like that for the South Africa region?

**Comment by OliverRC** [comment]
Not that I can see. I uploaded a file just to test and had a look at the urls and it seems the same as all the other regions:
https://elasticbeanstalk-af-south-1-xxxxx.s3.af-south-1.amazonaws.com/test/image.png

**Comment by einaregilsson** [comment]
Ok, I'll try to figure it out the next time I work on this.

**Comment by craig95** [comment]
> Yes. Seems like this workflow does not yet support south africa region. I ended up changing into a different solution.

@dryleaf Can you share the different solution you used?

**Comment by dryleaf** [comment]
```
- name: Deploy to Beanstalk
        uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: 'deploy ${{ secrets.EB_ENV_NAME }} --label v${{ steps.version_extractor.outputs.ARTIFACT_VERSION }}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "af-south-1"
```

**Comment by craig95** [comment]
@Niko-Kk you are correct I also came to the same code edits as PR (#47).

I guess the reason no error message is printed is that checking if the file already exists in the bucket is a HEAD request. If I skip this check and try upload it gives the following message:

> **IllegalLocationConstraintException** The af-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.

I got a similar error while setting up Amazon CloudFront to point to a bucket in af-south-1. The solution there was also to add the region in the host i.e. BUCKET_NAME.s3.REGION.amazonaws.com. 

@einaregilsson to solve this issue you can merge PR (#47) or I could make another PR that allows you to optionally specify a region for the bucket domain?

For now, I will be using @Niko-Kk's fork...

**Comment by OliverRC** [comment]
Nice one @craig95 . What I don't get though is AWS is supposed to be a commodity service and therefore there should be no difference from one region to another (except for may China which I get). So this seems broken on Amazons side too.

**Comment by einaregilsson** [comment]
Just merged this old pull request in so now region-specific buckets are used. Try using v17 and see if it works for you :)

**Comment by craig95** [comment]
@einaregilsson Awesome thank you very much! Can confirm v17 it is working!
