### ISSUE TITLE
Is it possible to deploy based on a docker container in ECR?

### ISSUE THREAD

**Issue by just-esra** [einaregilsson/beanstalk-deploy#30]
Hi,

Is it possible to use beanstalk-deploy to deploy to Elastic Beanstalk from a docker container in ECR using the repo url and tag? 

Thanks,

Esra

**Comment by einaregilsson** [comment]
How? You mean by using it as a command line script?

**Comment by yong-jie** [comment]
I found that it is possible. In your Dockerrun.aws.json you'd have to specify the ECR repo and tag. Mine starts from a [templated format](https://github.com/opengovsg/GoGovSG/blob/367d5992dd94d0c50cceefd7e71525f743fcec95/Dockerrun.aws.json#L4) which then gets [replaced in a workflow's step](https://github.com/opengovsg/GoGovSG/blob/25c205089f2ee1d1170466ce4a443b20580ec18a/.github/workflows/ci.yml#L85-L87).

After that, you can just zip up the Dockerrun.aws.json into deploy.zip and use `beanstalk-deploy` to deploy it to elastic beanstalk!

**Comment by einaregilsson** [comment]
Thanks for the answer. Closing this issue.
