### ISSUE TITLE
Use uploaded file in S3 if it does exist

### ISSUE THREAD

**Issue by Amraneze** [einaregilsson/beanstalk-deploy#34]
I'm getting this after trying to rebuild the github's workflow

```
##[error]Deployment failed: Error: Version ${ APP_NAME  }-${ github.sha } already exists in S3!
```

Which is normal because the build failed but the package is uploaded the S3 bucket. So is there something to not throw an error but instead of it to use the existing package from the bucket ?

I'm using version 10 (einaregilsson/beanstalk-deploy@v10)

```
          AWS Region: ${ AWS_REGION }
          File: ${ APP_NAME }-${ github.sha }.zip
          AWS Access Key: 20 characters long, starts with X
          AWS Secret Key: 40 characters long, starts with X
          Wait for deployment: true
          Recovery wait time: 30
```

Thank you 👍

**Comment by einaregilsson** [comment]
You can use the `use_existing_version_if_available` property and set it to `True` for that.
