### ISSUE TITLE
[Question] Do you have plan to deliver .ebextention files to beanstalk?

### ISSUE THREAD

**Issue by beanbroker** [einaregilsson/beanstalk-deploy#37]
Thx for your great plug-in for deploy!

I am wondering you have a plan to upgrade for delivery .ebextention files to beanstalk?

**Comment by einaregilsson** [comment]
No current plan. Isn't it enough to just have them in the zip file? Is there a special API you have to call?

**Comment by benswinburne** [comment]
Yeah it is fine to have them in the zip file, it runs them after it extracts.

Is it perhaps the case that the zip command you're running isn't including hidden files?

    zip -r deploy.zip . -x '*.git*'

Will include all files including hidden ones (and exclude .git). A lot of examples use `zip -r deploy.zip *` which doesn't include hidden files and directories.

**Comment by benswinburne** [comment]
I just noticed that the example in the readme only zips a subset of filetypes and would exclude *.config as it's not explicitly listed. @einaregilsson is it worth tweaking the example in the readme perhaps?

@beanbroker just make sure the zip command you're running gets all the files you want to deploy and it'll work fine.

**Comment by einaregilsson** [comment]
Good idea. I'm updating the action today, will change the README at the same time. Thanks.

**Comment by einaregilsson** [comment]
Just released v11, which adds this in the readme.

**Comment by beanbroker** [comment]
@benswinburne @einaregilsson THX!
