### ISSUE TITLE
License for repository.

### ISSUE THREAD

**Issue by bhautikpip** [einaregilsson/beanstalk-deploy#41]
Hi @einaregilsson ,

Are you planning to add license to this repository? I am planning on using/contributing to this package so just thought licensing makes things much easier.

Regards,
Bhautik

**Comment by bhautikpip** [comment]
Never mind I saw package.json file. Thanks!

**Comment by einaregilsson** [comment]
> I am planning on using/contributing to this package so just thought licensing makes things much easier.

If you're planning on sending a pull request I recommend opening an issue first so we can discuss the feature and whether it's something I would want to merge in. Some of the pull requests I get are for very niche features and I don't always accept them if I don't think they have value for the majority of users.

**Comment by bhautikpip** [comment]
Hi,

Do you mind adding license to the root level of the repo? it's easier to find that way. (https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository)

**Comment by einaregilsson** [comment]
Done.
