### ISSUE TITLE
Environment status not just Green

### ISSUE THREAD

**Issue by WezBacon** [einaregilsson/beanstalk-deploy#46]
I wonder if its worth adding an option to specify acceptable environment "states" (colours).

This is useful to be able to deploy to a scaled-down environment. For example; in a staging environment that gets automatically shutdown overnight I would want to deploy the code before any instances have been scaled up. This saves time on deploying new code to such environments, especially when an immutable deployment policy is used. In such a scenario the environment would never get to be green and so the deployment would "fail" but of course it hasn't actually failed at all. Using wait_for_deployment doesnt help because it just fires and forgets.

**Comment by einaregilsson** [comment]
I don't think that's a common enough requirement that I'd want to add the increased complexity it would entail. At the very least this issue would have to get a large number of upvotes before I'd consider adding it.

You might be better off just making a simple fork off this repo and adding the feature there :)
