### ISSUE TITLE
Deployment for Go app

### ISSUE THREAD

**Issue by D-sense** [einaregilsson/beanstalk-deploy#52]
Hi.

Please has anyone used this action to deploy a Go app? I am a bit confused about how this action will handle the Go application build.

Thank you.

**Comment by einaregilsson** [comment]
I mean, what is the normal way to deploy Go apps to Elastic Beanstalk? Isn't it just zipping the binary up?

One way to figure it out would be to first deploy once with the ´eb´ command line tool, then just go into S3, look at the zip file that the command line tool updated and see what the structure looks like, then make a zip like that for using with the GitHub action.

**Comment by D-sense** [comment]
@einaregilsson , thanks a lot. I did just that and it worked!

**Comment by einaregilsson** [comment]
Great  🙂

**Comment by D-sense** [comment]
Please is there a way to generate unique value for `version_label`? Probably, using date or number.

**Comment by einaregilsson** [comment]
You can use the environment variable $GITHUB_RUN_NUMBER for that. It's in incrementing id for the workflow.

Put in something like:
`
version_label: ${{env.GITHUB_RUN_NUMBER}}`

**Comment by D-sense** [comment]
> ${{env.GITHUB_RUN_NUMBER}}

That works. Thanks!
