### ISSUE TITLE
Additional special characters in version_description causing 403 error 

### ISSUE THREAD

**Issue by Kieran-rP** [einaregilsson/beanstalk-deploy#53]
I'm getting a 403 error when deploying my application.
The problem seems to be my application version string `0.0.0-dev+440e3f0` which uses the `+` character to add commit hash metadata to the version number (as permitted by [the semver spec](https://semver.org/#spec-item-10))

This looks to be the same issue as https://github.com/einaregilsson/beanstalk-deploy/issues/28 (and in particular @einaregilsson's fix mentioned [here](https://github.com/einaregilsson/beanstalk-deploy/issues/28#issuecomment-721676483) addresses some special characters, but not `+`). 

Would it be possible to add `+` to the list of allowed (and escaped) characters?

**Comment by einaregilsson** [comment]
I just tried this and it worked for me. 

![Screenshot 2021-02-08 at 13 02 12](https://user-images.githubusercontent.com/557149/107223392-0cb1d700-6a0e-11eb-8375-07459f737a1a.png)

Did you perhaps mean the `version_label`, not the `version_description`?

**Comment by einaregilsson** [comment]
The version label gets used for the filename in S3 and I'm not sure that allows + in it.

**Comment by einaregilsson** [comment]
This should be fixed in version 15. We now change any characters that's not alphanumeric, a dash or and underscore in the S3 filename and replace it with a dash. But the version label in Elastic Beanstalk keeps all the special characters.

**Comment by einaregilsson** [comment]
Sorry, use v16 instead, that fixes some additional issues with * in version description and truncates commit messages that are too long to be used as a version description 🙂

**Comment by Kieran-rP** [comment]
Awesome! Thanks @einaregilsson!
