### ISSUE TITLE
502 Bad Gateway after running this action

### ISSUE THREAD

**Issue by Warkanlock** [einaregilsson/beanstalk-deploy#56]
I'm currently having issues with my project while deployment.

A Bad Gateway message appears and throws a failed status into the test, but everything was right in terms of artifacts (even the deployment was successfully deployed on the server)

```Deployment failed: Error: Status: 502. Message: <html>```

Any insights?

**Comment by einaregilsson** [comment]
So the deployment was successful, but afterwards the app doesn't work? Have you tried deploying the exact same thing with the `eb` command line tool, see if that works normally?

**Comment by Warkanlock** [comment]
> So the deployment was successful, but afterwards the app doesn't work? Have you tried deploying the exact same thing with the `eb` command line tool, see if that works normally?

Seems like AWS was having trouble with incoming requests. Now it's working excellent! I'll close this

**Comment by einaregilsson** [comment]
@Warkanlock Great, thanks for letting me know 🙂
