### ISSUE TITLE
[UX] use_existing_version_if_available unexpectedly crashes if no environment is set

### ISSUE THREAD

**Issue by n-hebert** [einaregilsson/beanstalk-deploy#68]
# Background 
On [beanstalk-deploy.js#L370](https://github.com/einaregilsson/beanstalk-deploy/blob/master/beanstalk-deploy.js#L370) there is a check for the environment name without a check for `use_existing_version_if_available` which will cause a crash if an existing version has already been uploaded.

This was counter to my expectations, as it should simply ignore the package if it exists (do nothing).

The benefit of this use-case is for GitHub Actions workflows that leverage matrices via running an upload-only job (no environment) and then reuse that package for several matrixed jobs. It is compound with another issue, #69.

# Steps To Reproduce
1. Create a job that only uploads an app version
2. Create a matrixed job that applies that app version to many environments (consider that some may crash, requiring a re-run of the workflow)
3. Re-run the workflow

## Expected Result
The step performing the upload skips its work where possible by checking for the app version and omitting the effort

## Actual Result
The app version needs to be manually deleted from EB to proceed normally through the workflow

**Comment by einaregilsson** [comment]
Hmmm, not sure about that one. The `use_existing_version_if_available` parameter was meant for deployment only, it feels weird to me to have an upload only version and not fail if the version already exists. But I can see how it's confusing with that parameter set to true. I'll have to think about it.

**Comment by n-hebert** [comment]
We were looking to add a check to avoid executing if the version already exists, but there doesn't seem to be too many good or clean ways to exit a GitHub Action early.

What would be your suggestion for workflows that fail a later step and need to be redeployed? From our vantage we see only a few options:
1. The fix as described above
2. Delete the deployed version manually in the error case (which is slow, opens to human error, can be problematic based on user permissions, etc.)
3. Apply clunky work-arounds conditionally executing `beanstalk-deploy` which seem to require allowing failures in our job, meaning downstream jobs could run wrongfully

Any other ideas?

As another thought, we could add another argument such as `deploy_existing_version_if_available` do what you had expected `use_existing_version_if_available` to do, and then have `use` be more general (including this case).

**Comment by einaregilsson** [comment]
Does your workflow not start by building your product? Generally I just trigger a new workflow run which builds with a new version number and deploys that if things fail. But I guess if the build is very big or takes a long time then you wouldn't want to do that.

But I guess allowing users to upload only but do nothing if `use_existing_version_if_available` is set to True is OK. I have no time to work on this now though, easiest thing for you to do is to just fork the repo, change line 370 so it just exits with 0 if the parameter is set to True and the version exists, and just use your fork.

**Comment by n-hebert** [comment]
Ah yes, we keep the version number as the git hash -- that may explain the mismatch in expectations. It is also going to be true for our larger builds, as you point out.

We've done as you have said and are testing it now, we'll send a PR if it works well 🙂
