### ISSUE TITLE
Minimal AWS IAM Policy required to work

### ISSUE THREAD

**Issue by TCFox** [einaregilsson/beanstalk-deploy#7]
I'm getting a variety of permissions errors trying to get this working. Is there an effective minimum IAM policy I need to apply to the AWS User who's keys I'm supplying to this GitHub Action?

**Comment by einaregilsson** [comment]
I'm not sure what the minimal policy is. I once tried to just use `eb deploy` to deploy again and again and added every permission violation to our policy but it became so much that I ended up just giving full access to elasticbeanstalk and write access to some S3 bucket and a couple of extra thing. But maybe the Elastic Beanstalk documentation has some info on this.

**Comment by owenandrews** [comment]
I'm not sure what the minimal policy is, but I've successfully used the `AWSElasticBeanstalkService ` role for a user.

**Comment by Sytten** [comment]
I am also looking for the minimal policy for deploying... This seems like it should be provided by AWS.

**Comment by einaregilsson** [comment]
> This seems like it should be provided by AWS.

Yes, I agree. Closing this issue, if someone ever posts a policy that works I'll link it in the README.
