### ISSUE TITLE
Implement exponential backoff

### ISSUE THREAD

**Issue by n-hebert** [einaregilsson/beanstalk-deploy#73]
Hello again :wave: 

We are running into too much throttling and rate limit exceptions when using this Action and reached out to Amazon.

They responded as follows:

```
In general, AWS recommends using an exponential backoff algorithm to calculate the sleep interval between API calls in order to use progressively longer waits between retries for consecutive error responses [2].

[2] Error retries and exponential backoff in AWS:
 https://docs.aws.amazon.com/general/latest/gr/api-retries.html
```
https://docs.aws.amazon.com/general/latest/gr/api-retries.html

It seems the current version 19 does not do exponential back-off but simply sleeps repeatedly.

A v20 with exponential back-off would be very helpful for those who are using matrixes deploying to many environments, to avoid crashing ourselves on the parallelism.

**Comment by n-hebert** [comment]
I'm working on this over at https://github.com/rewindio/beanstalk-deploy/

Hopefully this is a desirable feature and a PR is desirable!

**Comment by einaregilsson** [comment]
@n-hebert Looks promising. Would definitely merge a PR with this if it's been tested and is working well. 🙂

**Comment by n-hebert** [comment]
This should be working in v20, thanks kindly @einaregilsson !
